{% set name = "hypso" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NTNU-SmallSat-Lab/hypso-package/archive/v{{ version }}.tar.gz
  sha256: ab19134d7b34108dfdd040c9336789cd82000169fd7f6a66be87099c67124267

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm  >=3.4
  run:
    - python >=3.9
    - numpy >=1.24
    - gdal =3.6.2
    - cartopy >=0.21.1
    - pandas
    - matplotlib-base
    - geopandas >=0.12.2
    - rasterio >=1.3.4
    - pyproj >=3.4.1
    - netcdf4 >=1.6.3
    - scikit-image >=0.21.0
    - py6s >=1.9.2
    - scipy >=1.11.2
    - pillow
    - shapely >=2.0.1
    - pysftp >=0.2.9

test:
  imports:
    - hypso
  commands:
    - pip check
    - pip list
  requires:
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/NTNU-SmallSat-Lab/hypso-package
  summary: 'HYPSO Toolbox For Satellite Image Processing'
  description: |
    hypso is a simple, fast visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF
    
